//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("KebajaDBModel", "announces_read_ibfk_1", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.users), "announces_read", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.announces_read), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "announces_read_ibfk_2", "messages", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.messages), "announces_read", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.announces_read), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "comments_ibfk_1", "messages", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.messages), "comments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.comments), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "comments_ibfk_2", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.users), "comments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.comments), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "likes_ibfk_1", "messages", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.messages), "likes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.likes), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "likes_ibfk_2", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.users), "likes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.likes), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "logins_ibfk_1", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.users), "logins", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.logins), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "messages_ibfk_1", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.users), "messages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.messages), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "messages_ibfk_2", "themes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.themes), "messages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.messages), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "subscriptions_ibfk_1", "users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.users), "subscriptions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.subscriptions), true)]
[assembly: EdmRelationshipAttribute("KebajaDBModel", "subscriptions_ibfk_2", "themes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(KebajaProject.Models.themes), "subscriptions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KebajaProject.Models.subscriptions), true)]

#endregion

namespace KebajaProject.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class KebajaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new KebajaEntities object using the connection string found in the 'KebajaEntities' section of the application configuration file.
        /// </summary>
        public KebajaEntities() : base("name=KebajaEntities", "KebajaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KebajaEntities object.
        /// </summary>
        public KebajaEntities(string connectionString) : base(connectionString, "KebajaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new KebajaEntities object.
        /// </summary>
        public KebajaEntities(EntityConnection connection) : base(connection, "KebajaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<announces_read> announces_read
        {
            get
            {
                if ((_announces_read == null))
                {
                    _announces_read = base.CreateObjectSet<announces_read>("announces_read");
                }
                return _announces_read;
            }
        }
        private ObjectSet<announces_read> _announces_read;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comments> comments
        {
            get
            {
                if ((_comments == null))
                {
                    _comments = base.CreateObjectSet<comments>("comments");
                }
                return _comments;
            }
        }
        private ObjectSet<comments> _comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<likes> likes
        {
            get
            {
                if ((_likes == null))
                {
                    _likes = base.CreateObjectSet<likes>("likes");
                }
                return _likes;
            }
        }
        private ObjectSet<likes> _likes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<logins> logins
        {
            get
            {
                if ((_logins == null))
                {
                    _logins = base.CreateObjectSet<logins>("logins");
                }
                return _logins;
            }
        }
        private ObjectSet<logins> _logins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<messages> messages
        {
            get
            {
                if ((_messages == null))
                {
                    _messages = base.CreateObjectSet<messages>("messages");
                }
                return _messages;
            }
        }
        private ObjectSet<messages> _messages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<subscriptions> subscriptions
        {
            get
            {
                if ((_subscriptions == null))
                {
                    _subscriptions = base.CreateObjectSet<subscriptions>("subscriptions");
                }
                return _subscriptions;
            }
        }
        private ObjectSet<subscriptions> _subscriptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<themes> themes
        {
            get
            {
                if ((_themes == null))
                {
                    _themes = base.CreateObjectSet<themes>("themes");
                }
                return _themes;
            }
        }
        private ObjectSet<themes> _themes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<users> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<users>("users");
                }
                return _users;
            }
        }
        private ObjectSet<users> _users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the announces_read EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToannounces_read(announces_read announces_read)
        {
            base.AddObject("announces_read", announces_read);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomments(comments comments)
        {
            base.AddObject("comments", comments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the likes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolikes(likes likes)
        {
            base.AddObject("likes", likes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologins(logins logins)
        {
            base.AddObject("logins", logins);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomessages(messages messages)
        {
            base.AddObject("messages", messages);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the subscriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosubscriptions(subscriptions subscriptions)
        {
            base.AddObject("subscriptions", subscriptions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the themes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTothemes(themes themes)
        {
            base.AddObject("themes", themes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(users users)
        {
            base.AddObject("users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="announces_read")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class announces_read : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new announces_read object.
        /// </summary>
        /// <param name="id_read">Initial value of the id_read property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        /// <param name="id_message">Initial value of the id_message property.</param>
        public static announces_read Createannounces_read(global::System.Int32 id_read, global::System.Int32 id_user, global::System.Int32 id_message)
        {
            announces_read announces_read = new announces_read();
            announces_read.id_read = id_read;
            announces_read.id_user = id_user;
            announces_read.id_message = id_message;
            return announces_read;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_read
        {
            get
            {
                return _id_read;
            }
            set
            {
                if (_id_read != value)
                {
                    Onid_readChanging(value);
                    ReportPropertyChanging("id_read");
                    _id_read = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_read");
                    Onid_readChanged();
                }
            }
        }
        private global::System.Int32 _id_read;
        partial void Onid_readChanging(global::System.Int32 value);
        partial void Onid_readChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_message
        {
            get
            {
                return _id_message;
            }
            set
            {
                Onid_messageChanging(value);
                ReportPropertyChanging("id_message");
                _id_message = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_message");
                Onid_messageChanged();
            }
        }
        private global::System.Int32 _id_message;
        partial void Onid_messageChanging(global::System.Int32 value);
        partial void Onid_messageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "announces_read_ibfk_1", "users")]
        public users users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.announces_read_ibfk_1", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.announces_read_ibfk_1", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<users> usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.announces_read_ibfk_1", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<users>("KebajaDBModel.announces_read_ibfk_1", "users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "announces_read_ibfk_2", "messages")]
        public messages messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.announces_read_ibfk_2", "messages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.announces_read_ibfk_2", "messages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<messages> messagesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.announces_read_ibfk_2", "messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<messages>("KebajaDBModel.announces_read_ibfk_2", "messages", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="comments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comments object.
        /// </summary>
        /// <param name="id_comment">Initial value of the id_comment property.</param>
        /// <param name="id_message">Initial value of the id_message property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        /// <param name="date_post">Initial value of the date_post property.</param>
        public static comments Createcomments(global::System.Int32 id_comment, global::System.Int32 id_message, global::System.Int32 id_user, global::System.DateTime date_post)
        {
            comments comments = new comments();
            comments.id_comment = id_comment;
            comments.id_message = id_message;
            comments.id_user = id_user;
            comments.date_post = date_post;
            return comments;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_comment
        {
            get
            {
                return _id_comment;
            }
            set
            {
                if (_id_comment != value)
                {
                    Onid_commentChanging(value);
                    ReportPropertyChanging("id_comment");
                    _id_comment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_comment");
                    Onid_commentChanged();
                }
            }
        }
        private global::System.Int32 _id_comment;
        partial void Onid_commentChanging(global::System.Int32 value);
        partial void Onid_commentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_message
        {
            get
            {
                return _id_message;
            }
            set
            {
                Onid_messageChanging(value);
                ReportPropertyChanging("id_message");
                _id_message = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_message");
                Onid_messageChanged();
            }
        }
        private global::System.Int32 _id_message;
        partial void Onid_messageChanging(global::System.Int32 value);
        partial void Onid_messageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_post
        {
            get
            {
                return _date_post;
            }
            set
            {
                Ondate_postChanging(value);
                ReportPropertyChanging("date_post");
                _date_post = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_post");
                Ondate_postChanged();
            }
        }
        private global::System.DateTime _date_post;
        partial void Ondate_postChanging(global::System.DateTime value);
        partial void Ondate_postChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "comments_ibfk_1", "messages")]
        public messages messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.comments_ibfk_1", "messages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.comments_ibfk_1", "messages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<messages> messagesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.comments_ibfk_1", "messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<messages>("KebajaDBModel.comments_ibfk_1", "messages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "comments_ibfk_2", "users")]
        public users users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.comments_ibfk_2", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.comments_ibfk_2", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<users> usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.comments_ibfk_2", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<users>("KebajaDBModel.comments_ibfk_2", "users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="likes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class likes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new likes object.
        /// </summary>
        /// <param name="id_like">Initial value of the id_like property.</param>
        /// <param name="id_message">Initial value of the id_message property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        public static likes Createlikes(global::System.Int32 id_like, global::System.Int32 id_message, global::System.Int32 id_user)
        {
            likes likes = new likes();
            likes.id_like = id_like;
            likes.id_message = id_message;
            likes.id_user = id_user;
            return likes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_like
        {
            get
            {
                return _id_like;
            }
            set
            {
                if (_id_like != value)
                {
                    Onid_likeChanging(value);
                    ReportPropertyChanging("id_like");
                    _id_like = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_like");
                    Onid_likeChanged();
                }
            }
        }
        private global::System.Int32 _id_like;
        partial void Onid_likeChanging(global::System.Int32 value);
        partial void Onid_likeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_message
        {
            get
            {
                return _id_message;
            }
            set
            {
                Onid_messageChanging(value);
                ReportPropertyChanging("id_message");
                _id_message = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_message");
                Onid_messageChanged();
            }
        }
        private global::System.Int32 _id_message;
        partial void Onid_messageChanging(global::System.Int32 value);
        partial void Onid_messageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "likes_ibfk_1", "messages")]
        public messages messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.likes_ibfk_1", "messages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.likes_ibfk_1", "messages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<messages> messagesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<messages>("KebajaDBModel.likes_ibfk_1", "messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<messages>("KebajaDBModel.likes_ibfk_1", "messages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "likes_ibfk_2", "users")]
        public users users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.likes_ibfk_2", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.likes_ibfk_2", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<users> usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.likes_ibfk_2", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<users>("KebajaDBModel.likes_ibfk_2", "users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="logins")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class logins : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new logins object.
        /// </summary>
        /// <param name="id_login">Initial value of the id_login property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        public static logins Createlogins(global::System.Int32 id_login, global::System.Int32 id_user)
        {
            logins logins = new logins();
            logins.id_login = id_login;
            logins.id_user = id_user;
            return logins;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_login
        {
            get
            {
                return _id_login;
            }
            set
            {
                if (_id_login != value)
                {
                    Onid_loginChanging(value);
                    ReportPropertyChanging("id_login");
                    _id_login = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_login");
                    Onid_loginChanged();
                }
            }
        }
        private global::System.Int32 _id_login;
        partial void Onid_loginChanging(global::System.Int32 value);
        partial void Onid_loginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "logins_ibfk_1", "users")]
        public users users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.logins_ibfk_1", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.logins_ibfk_1", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<users> usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.logins_ibfk_1", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<users>("KebajaDBModel.logins_ibfk_1", "users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="messages")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class messages : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new messages object.
        /// </summary>
        /// <param name="id_message">Initial value of the id_message property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        /// <param name="id_theme">Initial value of the id_theme property.</param>
        /// <param name="date_post">Initial value of the date_post property.</param>
        /// <param name="answer_to">Initial value of the answer_to property.</param>
        /// <param name="is_announce">Initial value of the is_announce property.</param>
        /// <param name="is_news">Initial value of the is_news property.</param>
        /// <param name="is_censored">Initial value of the is_censored property.</param>
        public static messages Createmessages(global::System.Int32 id_message, global::System.Int32 id_user, global::System.Int32 id_theme, global::System.DateTime date_post, global::System.Int32 answer_to, global::System.Boolean is_announce, global::System.Boolean is_news, global::System.Boolean is_censored)
        {
            messages messages = new messages();
            messages.id_message = id_message;
            messages.id_user = id_user;
            messages.id_theme = id_theme;
            messages.date_post = date_post;
            messages.answer_to = answer_to;
            messages.is_announce = is_announce;
            messages.is_news = is_news;
            messages.is_censored = is_censored;
            return messages;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_message
        {
            get
            {
                return _id_message;
            }
            set
            {
                if (_id_message != value)
                {
                    Onid_messageChanging(value);
                    ReportPropertyChanging("id_message");
                    _id_message = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_message");
                    Onid_messageChanged();
                }
            }
        }
        private global::System.Int32 _id_message;
        partial void Onid_messageChanging(global::System.Int32 value);
        partial void Onid_messageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_theme
        {
            get
            {
                return _id_theme;
            }
            set
            {
                Onid_themeChanging(value);
                ReportPropertyChanging("id_theme");
                _id_theme = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_theme");
                Onid_themeChanged();
            }
        }
        private global::System.Int32 _id_theme;
        partial void Onid_themeChanging(global::System.Int32 value);
        partial void Onid_themeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_post
        {
            get
            {
                return _date_post;
            }
            set
            {
                Ondate_postChanging(value);
                ReportPropertyChanging("date_post");
                _date_post = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_post");
                Ondate_postChanged();
            }
        }
        private global::System.DateTime _date_post;
        partial void Ondate_postChanging(global::System.DateTime value);
        partial void Ondate_postChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 answer_to
        {
            get
            {
                return _answer_to;
            }
            set
            {
                Onanswer_toChanging(value);
                ReportPropertyChanging("answer_to");
                _answer_to = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("answer_to");
                Onanswer_toChanged();
            }
        }
        private global::System.Int32 _answer_to;
        partial void Onanswer_toChanging(global::System.Int32 value);
        partial void Onanswer_toChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_announce
        {
            get
            {
                return _is_announce;
            }
            set
            {
                Onis_announceChanging(value);
                ReportPropertyChanging("is_announce");
                _is_announce = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_announce");
                Onis_announceChanged();
            }
        }
        private global::System.Boolean _is_announce;
        partial void Onis_announceChanging(global::System.Boolean value);
        partial void Onis_announceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_news
        {
            get
            {
                return _is_news;
            }
            set
            {
                Onis_newsChanging(value);
                ReportPropertyChanging("is_news");
                _is_news = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_news");
                Onis_newsChanged();
            }
        }
        private global::System.Boolean _is_news;
        partial void Onis_newsChanging(global::System.Boolean value);
        partial void Onis_newsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_censored
        {
            get
            {
                return _is_censored;
            }
            set
            {
                Onis_censoredChanging(value);
                ReportPropertyChanging("is_censored");
                _is_censored = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_censored");
                Onis_censoredChanged();
            }
        }
        private global::System.Boolean _is_censored;
        partial void Onis_censoredChanging(global::System.Boolean value);
        partial void Onis_censoredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "announces_read_ibfk_2", "announces_read")]
        public EntityCollection<announces_read> announces_read
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<announces_read>("KebajaDBModel.announces_read_ibfk_2", "announces_read");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<announces_read>("KebajaDBModel.announces_read_ibfk_2", "announces_read", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "comments_ibfk_1", "comments")]
        public EntityCollection<comments> comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<comments>("KebajaDBModel.comments_ibfk_1", "comments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<comments>("KebajaDBModel.comments_ibfk_1", "comments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "likes_ibfk_1", "likes")]
        public EntityCollection<likes> likes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<likes>("KebajaDBModel.likes_ibfk_1", "likes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<likes>("KebajaDBModel.likes_ibfk_1", "likes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "messages_ibfk_1", "users")]
        public users users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.messages_ibfk_1", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.messages_ibfk_1", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<users> usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.messages_ibfk_1", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<users>("KebajaDBModel.messages_ibfk_1", "users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "messages_ibfk_2", "themes")]
        public themes themes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<themes>("KebajaDBModel.messages_ibfk_2", "themes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<themes>("KebajaDBModel.messages_ibfk_2", "themes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<themes> themesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<themes>("KebajaDBModel.messages_ibfk_2", "themes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<themes>("KebajaDBModel.messages_ibfk_2", "themes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="subscriptions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class subscriptions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new subscriptions object.
        /// </summary>
        /// <param name="id_sub">Initial value of the id_sub property.</param>
        /// <param name="id_user">Initial value of the id_user property.</param>
        /// <param name="id_theme">Initial value of the id_theme property.</param>
        public static subscriptions Createsubscriptions(global::System.Int32 id_sub, global::System.Int32 id_user, global::System.Int32 id_theme)
        {
            subscriptions subscriptions = new subscriptions();
            subscriptions.id_sub = id_sub;
            subscriptions.id_user = id_user;
            subscriptions.id_theme = id_theme;
            return subscriptions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_sub
        {
            get
            {
                return _id_sub;
            }
            set
            {
                if (_id_sub != value)
                {
                    Onid_subChanging(value);
                    ReportPropertyChanging("id_sub");
                    _id_sub = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_sub");
                    Onid_subChanged();
                }
            }
        }
        private global::System.Int32 _id_sub;
        partial void Onid_subChanging(global::System.Int32 value);
        partial void Onid_subChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                Onid_userChanging(value);
                ReportPropertyChanging("id_user");
                _id_user = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_user");
                Onid_userChanged();
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_theme
        {
            get
            {
                return _id_theme;
            }
            set
            {
                Onid_themeChanging(value);
                ReportPropertyChanging("id_theme");
                _id_theme = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_theme");
                Onid_themeChanged();
            }
        }
        private global::System.Int32 _id_theme;
        partial void Onid_themeChanging(global::System.Int32 value);
        partial void Onid_themeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "subscriptions_ibfk_1", "users")]
        public users users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.subscriptions_ibfk_1", "users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.subscriptions_ibfk_1", "users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<users> usersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<users>("KebajaDBModel.subscriptions_ibfk_1", "users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<users>("KebajaDBModel.subscriptions_ibfk_1", "users", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "subscriptions_ibfk_2", "themes")]
        public themes themes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<themes>("KebajaDBModel.subscriptions_ibfk_2", "themes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<themes>("KebajaDBModel.subscriptions_ibfk_2", "themes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<themes> themesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<themes>("KebajaDBModel.subscriptions_ibfk_2", "themes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<themes>("KebajaDBModel.subscriptions_ibfk_2", "themes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="themes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class themes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new themes object.
        /// </summary>
        /// <param name="id_theme">Initial value of the id_theme property.</param>
        /// <param name="title">Initial value of the title property.</param>
        public static themes Createthemes(global::System.Int32 id_theme, global::System.String title)
        {
            themes themes = new themes();
            themes.id_theme = id_theme;
            themes.title = title;
            return themes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_theme
        {
            get
            {
                return _id_theme;
            }
            set
            {
                if (_id_theme != value)
                {
                    Onid_themeChanging(value);
                    ReportPropertyChanging("id_theme");
                    _id_theme = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_theme");
                    Onid_themeChanged();
                }
            }
        }
        private global::System.Int32 _id_theme;
        partial void Onid_themeChanging(global::System.Int32 value);
        partial void Onid_themeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "messages_ibfk_2", "messages")]
        public EntityCollection<messages> messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<messages>("KebajaDBModel.messages_ibfk_2", "messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<messages>("KebajaDBModel.messages_ibfk_2", "messages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "subscriptions_ibfk_2", "subscriptions")]
        public EntityCollection<subscriptions> subscriptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<subscriptions>("KebajaDBModel.subscriptions_ibfk_2", "subscriptions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<subscriptions>("KebajaDBModel.subscriptions_ibfk_2", "subscriptions", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KebajaDBModel", Name="users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new users object.
        /// </summary>
        /// <param name="id_user">Initial value of the id_user property.</param>
        /// <param name="user_rank">Initial value of the user_rank property.</param>
        /// <param name="rights">Initial value of the rights property.</param>
        /// <param name="surname">Initial value of the surname property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static users Createusers(global::System.Int32 id_user, global::System.String user_rank, global::System.Int32 rights, global::System.String surname, global::System.String name)
        {
            users users = new users();
            users.id_user = id_user;
            users.user_rank = user_rank;
            users.rights = rights;
            users.surname = surname;
            users.name = name;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_user
        {
            get
            {
                return _id_user;
            }
            set
            {
                if (_id_user != value)
                {
                    Onid_userChanging(value);
                    ReportPropertyChanging("id_user");
                    _id_user = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_user");
                    Onid_userChanged();
                }
            }
        }
        private global::System.Int32 _id_user;
        partial void Onid_userChanging(global::System.Int32 value);
        partial void Onid_userChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String user_rank
        {
            get
            {
                return _user_rank;
            }
            set
            {
                Onuser_rankChanging(value);
                ReportPropertyChanging("user_rank");
                _user_rank = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("user_rank");
                Onuser_rankChanged();
            }
        }
        private global::System.String _user_rank;
        partial void Onuser_rankChanging(global::System.String value);
        partial void Onuser_rankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rights
        {
            get
            {
                return _rights;
            }
            set
            {
                OnrightsChanging(value);
                ReportPropertyChanging("rights");
                _rights = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rights");
                OnrightsChanged();
            }
        }
        private global::System.Int32 _rights;
        partial void OnrightsChanging(global::System.Int32 value);
        partial void OnrightsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "announces_read_ibfk_1", "announces_read")]
        public EntityCollection<announces_read> announces_read
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<announces_read>("KebajaDBModel.announces_read_ibfk_1", "announces_read");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<announces_read>("KebajaDBModel.announces_read_ibfk_1", "announces_read", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "comments_ibfk_2", "comments")]
        public EntityCollection<comments> comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<comments>("KebajaDBModel.comments_ibfk_2", "comments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<comments>("KebajaDBModel.comments_ibfk_2", "comments", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "likes_ibfk_2", "likes")]
        public EntityCollection<likes> likes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<likes>("KebajaDBModel.likes_ibfk_2", "likes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<likes>("KebajaDBModel.likes_ibfk_2", "likes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "logins_ibfk_1", "logins")]
        public EntityCollection<logins> logins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<logins>("KebajaDBModel.logins_ibfk_1", "logins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<logins>("KebajaDBModel.logins_ibfk_1", "logins", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "messages_ibfk_1", "messages")]
        public EntityCollection<messages> messages
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<messages>("KebajaDBModel.messages_ibfk_1", "messages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<messages>("KebajaDBModel.messages_ibfk_1", "messages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KebajaDBModel", "subscriptions_ibfk_1", "subscriptions")]
        public EntityCollection<subscriptions> subscriptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<subscriptions>("KebajaDBModel.subscriptions_ibfk_1", "subscriptions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<subscriptions>("KebajaDBModel.subscriptions_ibfk_1", "subscriptions", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
